package-lock.json, package.json, src/components/MainSwiper.jsx, src/pages/MainPage.jsx, src/style/mainPage.scss
=> Feat: Main

src/components/Header.jsx, src/pages/LoginPage.jsx, src/store/index.js, src/store/modules/user.js
=> Feat:login axios

src/components/Header.jsx, src/style/_header.scss
=> Feat:header

src/pages/LoginPage.jsx, src/pages/RegisterPage.jsx
=> Feat: 회원가입 백엔드연동

src/pages/RegisterPage.jsx
=> Feat :  회원가입/ 닉네임 중복처리 백엔드 연동

src/pages/LoginPage.jsx
=> Feat: 로그인 백엔드 연동

src/components/Header.jsx, src/style/_header.scss
=> Design: Header 검색창 디자인

src/components/Header.jsx, src/style/_header.scss
=> Feat: 검색창 키워드, 최근 검색어 기능

src/components/Header.jsx, src/style/_header.scss
=> Design: 검색창 디자인 수정

src/App.js, src/components/Header.jsx, src/pages/AllProductPage.jsx, src/style/_header.scss
=> Feat: 검색창 통신

src/App.js, src/components/Header.jsx, src/pages/LoginFail.jsx, src/pages/MainPage.jsx, src/pages/SalePage.jsx
=> FEAT:Sale 백 연동 성공

src/pages/SalePage.jsx, src/style/sale.scss
=> Refactor:tag

src/components/Header.jsx
=> REFACTOR : HEADER 수정

src/pages/SalePage.jsx, src/style/_reset.scss, src/style/myPage.scss, src/style/sale.scss
=> Feat:이미지 첨부파일

src/App.js, src/components/mainPage/Category.jsx, src/pages/ProductDetailsPage.jsx, src/style/productDetails.scss
=> Feat: 상품 상세 페이지

src/components/mainPage/Category.jsx, src/components/mainPage/NewItems.jsx, src/pages/ProductDetailsPage.jsx, src/style/productDetails.scss
=> Feat: ProductDetailsPage 통신

src/pages/SalePage.jsx, src/style/_reset.scss, src/style/sale.scss
=> Feat:radio추가

src/pages/MyPage.jsx, src/style/myPage.scss
=> Feat:MyPage.jsx 코드 수정

src/App.js, src/pages/MyPage.jsx, src/style/myPage.scss
=> Refactor:MyPage.jsx 코드 수정

src/apis/item.js, src/pages/AllProductPage.jsx, src/pages/LoginPage.jsx, src/pages/SalePage.jsx
=> Feat : 각종수정

src/pages/ProductDetailsPage.jsx
Feat: productDetail 페이지 위시리스트 post 통신
=> Feat: productDetail 페이지 위시리스트 post 통신

src/pages/ProductDetailsPage.jsx
Feat: productDetail 위시리스트 get통신
=> Feat: productDetail 위시리스트 get통신

src/pages/ProductDetailsPage.jsx, src/style/productDetails.scss
=> Design: productdetail css 수정

src/style/productDetails.scss
=> Design: productdetail 수정

package-lock.json, package.json, src/App.js, src/components/Header.jsx, src/components/ScrollReset.jsx, src/pages/LoginPage.jsx, src/pages/MainPage.jsx, src/pages/ProductDetailsPage.jsx, src/pages/SalePage.jsx, src/style/_header.scss, src/style/bottomBtn.scss, src/style/category.scss, src/style/login.scss, src/style/mainPage.scss, src/style/newItems.scss, src/style/productDetails.scss, src/style/sale.scss, src/style/topBtn.scss
=> Feat:scrollReset

src/apis/user.js, src/components/myPage/TopBox.jsx, src/style/myPage.scss
=> Refactor:TopBox.jsx 수정

src/apis/mypage.js, src/apis/user.js, src/components/myPage/Like.jsx, src/components/myPage/MainContent.jsx, src/components/myPage/TopBox.jsx, src/components/myPage/Transction.jsx, src/pages/MyPage.jsx
=> Feat:mypage.js

src/apis/mypage.js, src/components/myPage/LeftBox.jsx, src/components/myPage/MainContent.jsx, src/components/myPage/TopBox.jsx, src/components/myPage/Transction.jsx, src/pages/MyPage.jsx, src/style/myPage.scss, src/style/mypage/leftbox.scss, src/style/mypage/topbox.scss
=> Refactor: Transcition.jsx 수정

src/apis/mypage.js, src/components/myPage/Like.jsx, src/components/myPage/MainContent.jsx, src/components/myPage/TopBox.jsx, src/components/myPage/Update.jsx, src/pages/MyPage.jsx, src/style/myPage.scss, src/style/mypage/update.scss
=> Feat: Update.jsx 통신

src/components/myPage/Transction.jsx, src/components/myPage/Update.jsx, src/style/mypage/update.scss
=> Feat: pagination 기능

src/components/myPage/Ready.jsx, src/components/myPage/Transction.jsx, src/pages/MyPage.jsx, src/style/myPage.scss, src/style/mypage/ready.scss
=> Feat: Ready.jsx

src/pages/MyStore.jsx, src/pages/SalePage.jsx
=> Feat:MyStore

src/apis/item.js, src/pages/MyPage.jsx, src/pages/SalePage.jsx, src/pages/UserStore.jsx, src/style/_header.scss
=> Refactor: salePage 이미지 코드수정

src/components/userStore/End.jsx, src/components/userStore/Ing.jsx
=> Refactor:mypage코드 수정

src/components/myPage/Update.jsx
=> Refactor: 비밀번호 암호화

src/apis/mypage.js, src/components/myPage/Transction.jsx, src/components/myPage/Update.jsx, src/components/userStore/End.jsx, src/components/userStore/Ing.jsx
=> Refactor: Update.jsx 수정

src/apis/mypage.js, src/components/myPage/Update.jsx
=> Refactor : Update.jsx 버튼

src/App.js, src/components/Header.jsx, src/components/header/Dropdown.jsx, src/components/userStore/TopBox.jsx, src/style/_header.scss, src/style/dropdown.scss, src/style/mypage/topbox.scss, src/style/userStore/storeTop.scss
=> Feat:dropdown

src/pages/ProductDetailsPage.jsx
=> Feat:Count 뽑기

src/components/Header.jsx
=> Refactor:검색창 랜덤키워드 수정

src/components/userStore/Ing.jsx, src/components/userStore/StatusChangeModal.jsx, src/style/userStore.scss
=> Design:myStore button

src/components/Header.jsx
=> Feat:드롭다운 닫기

src/components/mainPage/Category.jsx, src/components/mainPage/NewItems.jsx, src/pages/AllProductPage.jsx
=> Feat: 최근 본 상품 중복 처리

src/components/Header.jsx
=> Refactor:dropdown

src/pages/SalePage.jsx
=> Refactor:이미지최대3장

src/components/mainPage/NewItems.jsx, src/pages/SalePage.jsx, src/style/category.scss, src/style/newItems.scss
=> Design:이미지크기

package-lock.json, package.json, src/App.js, src/components/ChatRoom.jsx, src/components/userStore/Ing.jsx, src/components/userStore/StatusChangeModal.jsx, src/pages/ProductDetailsPage.jsx, src/style/chatRoom.scss, src/style/mypage/topbox.scss, src/style/userStore.scss
=> Feat:chatRoom

src/App.js, src/components/Header.jsx, src/pages/NotUpdating.jsx, src/pages/ProductDetailsPage.jsx, src/style/_header.scss, src/style/dropdown.scss, src/style/notUpdating.scss, src/style/productDetails.scss
=> Feat:NotUpdating

src/components/Footer.jsx, src/components/Header.jsx, src/components/userStore/End.jsx, src/components/userStore/Ing.jsx, src/components/userStore/TopBox.jsx, src/pages/SalePage.jsx, src/pages/UserStore.jsx, src/style/userStore.scss
=> Feat:userStore count

package-lock.json, src/components/myPage/Like.jsx, src/components/myPage/Transction.jsx, src/components/myPage/Update.jsx, src/style/myPage.scss, src/style/mypage/update.scss
=> Feat:Like.jsx 체크박스

src/components/myPage/Update.jsx
=> Feat : Update.jsx 수정
